/**
 * מיפוי שם יישוב (כפי שמופיע במאגר data.gov.il / למ"ס) → קוד אזור DogMate.
 * מפתחות חייבים להתאים לערך ה־value בבורר הערים (normalizeName).
 * נוצר ב־scripts/generateCityToDistrictMap.mjs (cityMapResolved.json + נפה).
 */

import type { DistrictOption } from '../constants/israelRegions';

/** אחד משמונת ערכי DISTRICT_OPTIONS */
export type DistrictValue = DistrictOption['value'];

/**
 * אובייקט מיפוי עיר → אזור (מפתח = שם יישוב בעברית, ייחודי).
 * כ־400 יישובים.
 */
export const CITY_TO_DISTRICT: Record<string, DistrictValue> = {
  // --- south_district ---
  'אוהד': 'south_district',
  'אופקים': 'south_district',
  'אילת': 'south_district',
  'איתן': 'south_district',
  'ארז': 'south_district',
  'אשדוד': 'south_district',
  'אשקלון': 'south_district',
  'באר גנים': 'south_district',
  'באר שבע': 'south_district',
  'בארי': 'south_district',
  'בטחה': 'south_district',
  'ברוש': 'south_district',
  'גבים': 'south_district',
  'גבעות בר': 'south_district',
  'גיאה': 'south_district',
  'גילת': 'south_district',
  'דימונה': 'south_district',
  'דקל': 'south_district',
  'זוהר': 'south_district',
  'זמרת': 'south_district',
  'חורה': 'south_district',
  'חצב': 'south_district',
  'חצבה': 'south_district',
  'יבול': 'south_district',
  'יהל': 'south_district',
  'ינון': 'south_district',
  'ירוחם': 'south_district',
  'ישע': 'south_district',
  'יתד': 'south_district',
  'יתיר': 'south_district',
  'כחלה': 'south_district',
  'כיסופים': 'south_district',
  'כנות': 'south_district',
  'להב': 'south_district',
  'להבים': 'south_district',
  'לוטן': 'south_district',
  'לכיש': 'south_district',
  'לקיה': 'south_district',
  'מגן': 'south_district',
  'מיתר': 'south_district',
  'מפלסים': 'south_district',
  'מצפה רמון': 'south_district',
  'משען': 'south_district',
  'נגבה': 'south_district',
  'נווה': 'south_district',
  'נועם': 'south_district',
  'נחלה': 'south_district',
  'נטע': 'south_district',
  'ניצן': 'south_district',
  'ניר עוז': 'south_district',
  'נירים': 'south_district',
  'נתיבות': 'south_district',
  'סופה': 'south_district',
  'סמר': 'south_district',
  'סעד': 'south_district',
  'סעוה': 'south_district',
  'ספיר': 'south_district',
  'עוזה': 'south_district',
  'עומר': 'south_district',
  'עוצם': 'south_district',
  'עזוז': 'south_district',
  'עזר': 'south_district',
  'עידן': 'south_district',
  'עין הבשור': 'south_district',
  'ערד': 'south_district',
  'פארן': 'south_district',
  'פטיש': 'south_district',
  'צוחר': 'south_district',
  'צופר': 'south_district',
  'קדמה': 'south_district',
  'קרית גת': 'south_district',
  'קרית מלאכי': 'south_district',
  'רהט': 'south_district',
  'רנן': 'south_district',
  'שדה דוד': 'south_district',
  'שדרות': 'south_district',
  'שובל': 'south_district',
  'שחר': 'south_district',
  'שני': 'south_district',
  'שקף': 'south_district',
  'תל שבע': 'south_district',

  // --- jerusalem_district ---
  'אבו גוש': 'jerusalem_district',
  'אדרת': 'jerusalem_district',
  'אורה': 'jerusalem_district',
  'בית שמש': 'jerusalem_district',
  'בקוע': 'jerusalem_district',
  'גבעת זאב': 'jerusalem_district',
  'גיזו': 'jerusalem_district',
  'גפן': 'jerusalem_district',
  'הראל': 'jerusalem_district',
  'זנוח': 'jerusalem_district',
  'ירושלים': 'jerusalem_district',
  'ישעי': 'jerusalem_district',
  'מבשרת ציון': 'jerusalem_district',
  'מוצא עילית': 'jerusalem_district',
  'מטע': 'jerusalem_district',
  'מעלה אדומים': 'jerusalem_district',
  'נחם': 'jerusalem_district',
  'נטף': 'jerusalem_district',
  'עגור': 'jerusalem_district',
  'צובה': 'jerusalem_district',
  'צור הדסה': 'jerusalem_district',
  'צרעה': 'jerusalem_district',
  'קרית יערים': 'jerusalem_district',

  // --- yosh_district ---
  'אלפי מנשה': 'yosh_district',
  'אריאל': 'yosh_district',
  'בית אל': 'yosh_district',
  'ביתר עילית': 'yosh_district',
  'יקיר': 'yosh_district',
  'כוכב יאיר': 'yosh_district',
  'מודיעין עילית': 'yosh_district',
  'עלי זהב': 'yosh_district',
  'עמנואל': 'yosh_district',
  'קרית ארבע': 'yosh_district',
  'קרני שומרון': 'yosh_district',
  'רבבה': 'yosh_district',

  // --- center_district ---
  'אזור': 'center_district',
  'באר טוביה': 'center_district',
  'באר יעקב': 'center_district',
  'בית גמליאל': 'center_district',
  'בית דגן': 'center_district',
  'בית חלקיה': 'center_district',
  'בית חנן': 'center_district',
  'בית עובד': 'center_district',
  'בית רבן': 'center_district',
  'בן זכאי': 'center_district',
  'בני דרום': 'center_district',
  'בני דרור': 'center_district',
  'בני ראם': 'center_district',
  'בניה': 'center_district',
  'גדרה': 'center_district',
  'גזר': 'center_district',
  'גמזו': 'center_district',
  'גן הדרום': 'center_district',
  'גן יבנה': 'center_district',
  'גן שורק': 'center_district',
  'גנות': 'center_district',
  'גני טל': 'center_district',
  'גני יוחנן': 'center_district',
  'גני תקווה': 'center_district',
  'זיתן': 'center_district',
  'חדיד': 'center_district',
  'חולדה': 'center_district',
  'חמד': 'center_district',
  'חפץ חיים': 'center_district',
  'טירה': 'center_district',
  'יבנה': 'center_district',
  'יגל': 'center_district',
  'יד בנימין': 'center_district',
  'יהוד-מונוסון': 'center_district',
  'יסודות': 'center_district',
  'יציץ': 'center_district',
  'ישרש': 'center_district',
  'כפר אביב': 'center_district',
  'כפר אחים': 'center_district',
  'כפר ביל"ו': 'center_district',
  'כפר ברא': 'center_district',
  'כפר ורבורג': 'center_district',
  'כפר קאסם': 'center_district',
  'לוד': 'center_district',
  'לפיד': 'center_district',
  'מודיעין-מכבים-רעות': 'center_district',
  'מזכרת בתיה': 'center_district',
  'מישר': 'center_district',
  'ניר צבי': 'center_district',
  'נס ציונה': 'center_district',
  'נען': 'center_district',
  'עיינות': 'center_district',
  'עין צורים': 'center_district',
  'עשרת': 'center_district',
  'פדיה': 'center_district',
  'פלמחים': 'center_district',
  'צופיה': 'center_district',
  'קלנסווה': 'center_district',
  'קרית עקרון': 'center_district',
  'ראשון לציון': 'center_district',
  'רחובות': 'center_district',
  'רמלה': 'center_district',
  'שדמה': 'center_district',
  'שוהם': 'center_district',
  'שערי תקווה': 'center_district',
  'תימורים': 'center_district',
  'תלמי יחיאל': 'center_district',
  'תלמי יפה': 'center_district',

  // --- gush_dan_district ---
  'אור יהודה': 'gush_dan_district',
  'אייל': 'gush_dan_district',
  'אלעד': 'gush_dan_district',
  'בני ברק': 'gush_dan_district',
  'ברקת': 'gush_dan_district',
  'בת ים': 'gush_dan_district',
  'גבעת שמואל': 'gush_dan_district',
  'גבעתיים': 'gush_dan_district',
  'חגור': 'gush_dan_district',
  'חולון': 'gush_dan_district',
  'כפר שמריהו': 'gush_dan_district',
  'מזור': 'gush_dan_district',
  'מעש': 'gush_dan_district',
  'מתן': 'gush_dan_district',
  'נופך': 'gush_dan_district',
  'סביון': 'gush_dan_district',
  'עינת': 'gush_dan_district',
  'פתח תקווה': 'gush_dan_district',
  'קרית אונו': 'gush_dan_district',
  'רמת גן': 'gush_dan_district',
  'תל אביב - יפו': 'gush_dan_district',

  // --- sharon_district ---
  'אביחיל': 'sharon_district',
  'אור עקיבא': 'sharon_district',
  'בחן': 'sharon_district',
  'בית ינאי': 'sharon_district',
  'בנימינה-גבעת עדה': 'sharon_district',
  'בצרה': 'sharon_district',
  'ג\'ת': 'sharon_district',
  'גן שמואל': 'sharon_district',
  'געש': 'sharon_district',
  'דור': 'sharon_district',
  'הוד השרון': 'sharon_district',
  'הרצליה': 'sharon_district',
  'זכרון יעקב': 'sharon_district',
  'זמר': 'sharon_district',
  'חגלה': 'sharon_district',
  'חדרה': 'sharon_district',
  'חופית': 'sharon_district',
  'חריש': 'sharon_district',
  'ינוב': 'sharon_district',
  'יעף': 'sharon_district',
  'יקום': 'sharon_district',
  'כפר ויתקין': 'sharon_district',
  'כפר יונה': 'sharon_district',
  'כפר סבא': 'sharon_district',
  'מאור': 'sharon_district',
  'מגל': 'sharon_district',
  'מכמורת': 'sharon_district',
  'מעגן מיכאל': 'sharon_district',
  'מצר': 'sharon_district',
  'נתניה': 'sharon_district',
  'עולש': 'sharon_district',
  'עופר': 'sharon_district',
  'עתלית': 'sharon_district',
  'פוריידיס': 'sharon_district',
  'פורת': 'sharon_district',
  'פרדס חנה-כרכור': 'sharon_district',
  'קדימה-צורן': 'sharon_district',
  'קציר': 'sharon_district',
  'רמת השרון': 'sharon_district',
  'רעננה': 'sharon_district',
  'שפיים': 'sharon_district',

  // --- haifa_district ---
  'אושה': 'haifa_district',
  'אפק': 'haifa_district',
  'אשבל': 'haifa_district',
  'אשחר': 'haifa_district',
  'אשרת': 'haifa_district',
  'אתגר': 'haifa_district',
  'בסמת טבעון': 'haifa_district',
  'בענה': 'haifa_district',
  'בצת': 'haifa_district',
  'גורן': 'haifa_district',
  'גיתה': 'haifa_district',
  'דאלית אל-כרמל': 'haifa_district',
  'הילה': 'haifa_district',
  'חוסן': 'haifa_district',
  'חיפה': 'haifa_district',
  'חלוץ': 'haifa_district',
  'טירת כרמל': 'haifa_district',
  'יגור': 'haifa_district',
  'יעד': 'haifa_district',
  'יערה': 'haifa_district',
  'יקנעם עילית': 'haifa_district',
  'ירכא': 'haifa_district',
  'כברי': 'haifa_district',
  'כליל': 'haifa_district',
  'כמון': 'haifa_district',
  'לבון': 'haifa_district',
  'לוטם': 'haifa_district',
  'לימן': 'haifa_district',
  'מורן': 'haifa_district',
  'מנוף': 'haifa_district',
  'מנות': 'haifa_district',
  'מתת': 'haifa_district',
  'נהריה': 'haifa_district',
  'נחף': 'haifa_district',
  'נשר': 'haifa_district',
  'סלמה': 'haifa_district',
  'סער': 'haifa_district',
  'עדי': 'haifa_district',
  'עכו': 'haifa_district',
  'עמקה': 'haifa_district',
  'פלך': 'haifa_district',
  'צביה': 'haifa_district',
  'קרית אתא': 'haifa_district',
  'קרית טבעון': 'haifa_district',
  'קרית ים': 'haifa_district',
  'קרית מוצקין': 'haifa_district',
  'ראמה': 'haifa_district',
  'רגבה': 'haifa_district',
  'רכסים': 'haifa_district',
  'רמת ישי': 'haifa_district',
  'שעב': 'haifa_district',

  // --- north_district ---
  'אודם': 'north_district',
  'אומן': 'north_district',
  'אלומות': 'north_district',
  'אפיק': 'north_district',
  'ארבל': 'north_district',
  'בית שאן': 'north_district',
  'ברעם': 'north_district',
  'ברק': 'north_district',
  'ג\'ש )גוש חלב(': 'north_district',
  'גבע': 'north_district',
  'גבעת אבני': 'north_district',
  'גבעת אלה': 'north_district',
  'גבעת חיים )איחוד(': 'north_district',
  'גבעת עוז': 'north_district',
  'גבעת שפירא': 'north_district',
  'גבת': 'north_district',
  'גדות': 'north_district',
  'גדיש': 'north_district',
  'גונן': 'north_district',
  'גזית': 'north_district',
  'גשור': 'north_district',
  'גשר': 'north_district',
  'דברת': 'north_district',
  'דוב"ב': 'north_district',
  'דחי': 'north_district',
  'דליה': 'north_district',
  'דן': 'north_district',
  'דפנה': 'north_district',
  'האון': 'north_district',
  'הזורעים': 'north_district',
  'חבר': 'north_district',
  'חולתה': 'north_district',
  'חזון': 'north_district',
  'חמאם': 'north_district',
  'חצור הגלילית': 'north_district',
  'טבריה': 'north_district',
  'טמרה': 'north_district',
  'יבנאל': 'north_district',
  'יובל': 'north_district',
  'יעל': 'north_district',
  'יפיע': 'north_district',
  'יפעת': 'north_district',
  'יפתח': 'north_district',
  'כחל': 'north_district',
  'כנף': 'north_district',
  'כפר בלום': 'north_district',
  'כפר הנשיא': 'north_district',
  'כפר חיטים': 'north_district',
  'כפר כנא': 'north_district',
  'כרמיאל': 'north_district',
  'כרמים': 'north_district',
  'לביא': 'north_district',
  'מגאר': 'north_district',
  'מגדל': 'north_district',
  'מגדל העמק': 'north_district',
  'מזרע': 'north_district',
  'מטולה': 'north_district',
  'מיטב': 'north_district',
  'מיצר': 'north_district',
  'מירב': 'north_district',
  'מלאה': 'north_district',
  'מנרה': 'north_district',
  'מסד': 'north_district',
  'מסדה': 'north_district',
  'מעגן': 'north_district',
  'מעין ברוך': 'north_district',
  'מעלה גמלא': 'north_district',
  'מעלות-תרשיחא': 'north_district',
  'מצפה': 'north_district',
  'משגב עם': 'north_district',
  'משהד': 'north_district',
  'נאות גולן': 'north_district',
  'נהלל': 'north_district',
  'נוב': 'north_district',
  'נווה אטי"ב': 'north_district',
  'נוף הגליל': 'north_district',
  'נטור': 'north_district',
  'ניין': 'north_district',
  'ניר דוד )תל עמל(': 'north_district',
  'נצרת': 'north_district',
  'סאסא': 'north_district',
  'סולם': 'north_district',
  'סח\'נין': 'north_district',
  'עין גב': 'north_district',
  'עין חרוד )איחוד(': 'north_district',
  'עין חרוד )מאוחד(': 'north_district',
  'עלמה': 'north_district',
  'עמיר': 'north_district',
  'עפולה': 'north_district',
  'פרוד': 'north_district',
  'צפת': 'north_district',
  'קלע': 'north_district',
  'קצרין': 'north_district',
  'קרית שמונה': 'north_district',
  'קשת': 'north_district',
  'ראש פינה': 'north_district',
  'רביד': 'north_district',
  'רמות': 'north_district',
  'שאר ישוב': 'north_district',
  'שעל': 'north_district',
  'שפר': 'north_district',
  'שפרעם': 'north_district',
  'תל קציר': 'north_district',

};

/**
 * מחזיר את קוד האזור לפי שם יישוב, או null אם אין במפה.
 */
export function getRegionByCity(cityName: string): DistrictValue | null {
  const key = cityName.replace(/\s+/g, ' ').trim();
  if (!key) return null;
  const hit = CITY_TO_DISTRICT[key];
  return hit ?? null;
}
